Accept=Onartu
Close=Itxi
Price= Prezioa
SelectOption=Aukeratu

MainGUI.CreateSale= Eskaintza sortu
MainGUI.QuerySales= Eskaintzak konstsultatu
MainGUI.SelectOption=Aukeratu
MainGUI.MainTitle=Merkatua
MainGUI.Registrarse= Erregistratu
MainGUI.HacerLogin= Saioa Hasi
MainGUI.AceptarOferta= Eskaintza Onartu
MainGUI.VerOfertasAceptadas= Ikusi Onartutako Eskaintzak

CreateSaleGUI.Title=Tituloa
CreateSaleGUI.Description=Deskripzioa
CreateSaleGUI.Status=Egoera
CreateSaleGUI.Category=Kategoria
CreateSaleGUI.Price=Prezioa
CreateSaleGUI.PriceMustBeGreaterThan0=Errorea, prezioa 0 baino handiagoa
CreateSaleGUI.ProductCreated=Eskaintza sortuta
CreateSaleGUI.CreateProduct=Sortu Eskaintza
CreateSaleGUI.ErrorNumber=Errorea, prezioa zenbaki bat izan behar da
CreateSaleGUI.ErrorQuery=Errorea, datuak falta dira
CreateSaleGUI.LoadPicture=Argazkia igo
CreateSaleGUI.PublicationDate=Argitarapen eguna

Registrarse.Correo=Posta Elektronikoa
Registrarse.Nombre=Izena
Registrarse.Contrasena=Pasahitza
Registrarse.Registrarse=Erregistratu
Registrarse.Vendedor=Saltzailea
Registrarse.Comprador=Eroslea
Registrarse.ErrorGmail=Errorea, mezu elektronikoak @gmail.com eduki behar du amaieran
Registrarse.ErrorTipo=Errorea, ez da kontu motarik hautatu
Registrarse.ErrorDuplicado=Errorea, erabiltzaile hori dagoeneko existitzen da
Registrarse.ErrorVacio=Errorea, eremu bat hutsik dago
Registrarse.Exito=Behar bezala erregistratu da

HacerLogin.Correo=Posta Elektronikoa
HacerLogin.HacerLogin=Saioa Hasi
HacerLogin.ErrorGmail=Errorea, erabiltzaile hori ez da existitzen
HacerLogin.ErrorContraseña=Errorea, pasahitza okerra da
HacerLogin.ErrorVacio=Errorea, eremu bat hutsik dago
HacerLogin.Exito=Saioa arrakastaz hasi da, ongi etorri!

ContraOferta.PrecioOriginal=Jatorrizko Prezioa
ContraOferta.PrecioOfrecido=Eskainitako Prezioa
ContraOferta.Compra=Hautatutako Eskaintza
ContraOferta.Confirmar=Baieztu
ContraOferta.ErrorVacio=Errorea, 0 baino handiagoa den zenbateko bat eskaini behar duzu
ContraOferta.ErrorSobrePrecio=Errorea, ezin duzu produktuaren prezioa baino gehiago eskaini
ContraOferta.Exito=Arrakastaz onartu da

VerOfertasAceptadasGUI.Titulo=Izenburua
VerOfertasAceptadasGUI.PrecioOriginal=Jatorrizko Prezioa
VerOfertasAceptadasGUI.Contraoferta=Kontraeskaintza
VerOfertasAceptadasGUI.Comprador=Eroslea
VerOfertasAceptadasGUI.SinContraofertas=Ez dago kontraeskaintzarik
VerOfertasAceptadasGUI.Contraofertas=Kontraeskaintzak
VerOfertasAceptadasGUI.BuscarProductos=Eskaintzak Bilatu

QuerySalesGUI.Search=Bilatu
QuerySalesGUI.NoProducts=Ez daude eskaintzak
QuerySalesGUI.Price=Prezioa
QuerySalesGUI.FindProducts=Eskaintzak bilatu
QuerySalesGUI.Products=Eskaintzak (Double-click eskaintza ikusteko)

ShowSaleGUI.Title=Eskaintza xehestasunak


DataAccess.SaleAlreadyExist=ERROR, Eskaintza existizen da
DataAccess.ErrorSaleMustBeLaterThanToday=ERROR, data gaur baino beranduago izan behar da
DataAccess.ErrorFileNotUploadedException=ERROR, Argazkia igo behar da